/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.avoidfrust.learn.gradle.releasePublish.projectA;

public class LibraryA {
    public boolean someLibraryMethod() {
        return true;
    }
}
