/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.avoidfrust.learn.gradle.vFiveSixFour;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
