/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.avoidfrust.learn.gradle.releasePublish.projectC;

import org.avoidfrust.learn.gradle.releasePublish.projectA.LibraryA;
import org.avoidfrust.learn.gradle.releasePublish.projectB.LibraryB;

public class LibraryC {
    public LibraryA someLibraryMethod() {
        return null;
    }
    public LibraryB someLibraryMethod2() {
        return null;
    }
}
