/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.avoidfrust.learn.gradle.releasePublish.projectB;

import org.avoidfrust.learn.gradle.releasePublish.projectA.LibraryA;

public class LibraryB {
    public LibraryA someLibraryMethod() {
        return null;
    }
}
